language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.1
    - android-23
    

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

before_script:
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:"16 --abi v7a
  - emulator -avd test -no-skin -no-audio -no-window &
script:
  - ./wait_for_emulator
  - ./gradlew connectedCheck -PdisablePreDex

